POST http://localhost:4899/company/register HTTP/1.1
content-type: application/json

{
    "firstName": "Eze",
    "lastName": "Noah",
    "email": "eze@example.com",
    "password": "password",
    "confirmPassword": "password"
}

### Get superAdmin Notidfication
POST http://localhost:4899/company/super-admin-notification HTTP/1.1
content-type: application/json

{
    "email": "jerry@example.com",
    "password": "password"
}

### login for company Admin
POST http://localhost:4899/company/login HTTP/1.1
content-type: application/json

{
    "firstName": "Eze",
    "lastName": "Noah",
    "email": "eze@example.com",
    "password": "password",
    "confirmPassword": "password"
}
